### PR TITLE
Fix fatal error when upgrading from v150629 with WP_DEBUG enabled.

### PR DESCRIPTION
**Pull request by raamdev**
See websharks/zencache#524

### CODE REVIEW

**Comment by vimes1984** [comment]
isn't this a perfect use case for a switch?

**Comment by raamdev** [comment]
@vimes1984 Which code are you referring to?

**Comment by vimes1984** [comment]
Maybe that was astupid question but hey I'm contributing !!!

**Comment by jaswrks** [comment]
@vimes1984 Great to see you here :-)
https://wordpress.org/support/topic/amazing-806

> isn't this a perfect use case for a switch?

Maybe. However, `switch(){}` is normally the most useful whenever there is more than a single condition against a specific value. I think `if() else if()` works best in this case; i.e., cleaner and easier to read in code.

**Pull request closed without merging**
