### PR TITLE
Improve WP_CACHE removal. See: websharks/zencache#509

### PR DESCRIPTION
**Pull request by jaswrks**
Closes websharks/zencache#509

### CODE REVIEW

**Comment by raamdev** [comment]
@jaswsinc How does this resolve #509? Your change here simply adds a check to see if `!is_writable($wp_config_file)`; it does not do anything about the issue of ending up with 2 `WP_CACHE` definitions inside `wp-config.php`... unless I'm missing something here?

**Comment by jaswrks** [comment]
To help illustrate the way this works, consider the following chain of events...

## MISSION A: Add `WP_CACHE` to `/wp-config.php`
- Remove existing `WP_CACHE` instance from `/wp-config.php`; if writable, regardless of existing value. Return true if we are able to remove. Or, if the existing value is false and the file is not writable.
- If writable, add new `WP_CACHE` instance into `/wp-config.php` file with a true value.
- _Finally, return true if able to remove and then add a true value as well._

---

Here is another use case for this method...

## MISSION B: Turn off `WP_CACHE` behavior in WordPress.
- Remove existing `WP_CACHE` instance from `/wp-config.php`; if writable, regardless of existing value. Return true if we are able to remove. Or, if the existing value is false and the file is not writable.

**Comment by raamdev** [comment]
> Return true if we are able to remove. Or, if the existing value is false and the file is not writable.

If the mission is to "Add `WP_CACHE` to `/wp-config.php`", why would you return true if the existing value is false and the file is not writable? That sounds backwards to me... despite `WP_CACHE` being set to _false_, you're returning true (the same value you would return if `WP_CACHE` were successfully removed and re-added with a _true_ value). 

Ha, I'm totally confused now. :-)

However, as I [noted above](https://github.com/websharks/zencache/pull/530#commitcomment-12382065), this updated code _does_ seem to resolve the issue described in #509, so I'm going to merge this.

**Comment by jaswrks** [comment]
> If the mission is to "Add WP_CACHE to /wp-config.php", why would you return true if the existing value is false and the file is not writable? That sounds backwards to me...

Correct. It doesn't make a lot of sense in that scenario, but it doesn't harm anything either; i.e., if the file is not writable we can't add `WP_CACHE` anyway. In short, the reason for this behavior is not for MISSION A.

It's because we need to satisfy both MISSION A and MISSION B. Those are the two use cases for this method. In the MISSION B example, returning true does make more sense; i.e., if we just want to disable `WP_CACHE` by removing it from the `/wp-config.php` file, and it's already false and not writable, then that's fine, and this method can return true.

**Comment by raamdev** [comment]
> In short, the reason for this behavior is not for MISSION A. It's because we need to satisfy both MISSION A and MISSION B
> [...]
> i.e., if we just want to disable WP_CACHE by removing it from the /wp-config.php file, and it's already false and not writable, then that's fine, and this method can return true.

Ah, yes, it makes perfect sense now. Thanks for explaining! :-)

**Pull request merged**
